// api/instagram/webhook.js - Public webhook for Instagram automation (no auth required)

const { supabase } = require('../../db/client');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const { classifyRegion } = require('../../classifyRegion');

module.exports = async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  if (!supabase) {
    return res.status(503).json({ error: 'Database not configured' });
  }

  try {
    const { mediaId, shortcode, permalink, caption } = req.body;
    
    if (!shortcode) {
      return res.status(400).json({ error: 'Missing shortcode parameter.' });
    }

    // Fetch current Instagram config to check if connected
    const { data: config } = await supabase
      .from('instagram_config')
      .select('*')
      .limit(1)
      .single();

    if (!config || !config.connected) {
      return res.status(403).json({ error: 'Instagram account integration is not connected.' });
    }

    // Log webhook event
    await supabase.from('instagram_logs').insert({
      message: `🔔 WEBHOOK EVENT RECEIVED: New post media detected. Shortcode: "${shortcode}" | Media ID: "${mediaId || 'unknown'}" | Caption: "${caption ? caption.substring(0, 60) + '...' : 'No caption'}"`,
      created_at: new Date().toISOString()
    });

    // Run Gemini pipeline
    await supabase.from('instagram_logs').insert({
      message: `Querying Gemini to write satirical chronicle...`,
      created_at: new Date().toISOString()
    });

    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    let aiOutput = null;

    if (GEMINI_API_KEY) {
      try {
        const genAI = new GoogleGenerativeAI(GEMINI_API_KEY);
        const model = genAI.getGenerativeModel({ 
          model: "gemini-1.5-flash",
          generationConfig: { responseMimeType: "application/json" }
        });

        const prompt = `
          You are the Head Editorial AI for "Honestly Biased", an independent Indian media platform.
          Transform this Instagram reel caption into a satirical news article.
          
          Instagram Caption: "${caption || 'Instagram Video Update'}"
          Shortcode: ${shortcode}
          
          Return JSON:
          {
            "category": "Politics|Tech|Finance|Entertainment|Health",
            "region": "indian|world|uk",
            "aiHeadline": "Satirical headline",
            "aiSummary": "2-sentence summary with bias",
            "biasAudit": "1-sentence structural critique",
            "fullBlog": "Full HTML blog post (3-4 paragraphs)"
          }
        `;

        const result = await model.generateContent(prompt);
        aiOutput = JSON.parse(result.response.text());
      } catch (aiErr) {
        console.error('Gemini webhook failed:', aiErr);
      }
    }

    // Fallback mock article
    if (!aiOutput) {
      const regions = ['indian', 'world', 'uk'];
      const categories = ['Politics', 'Tech', 'Finance', 'Entertainment', 'Health'];
      
      aiOutput = {
        category: categories[Math.floor(Math.random() * categories.length)],
        region: regions[Math.floor(Math.random() * regions.length)],
        aiHeadline: `Simulated: ${(caption || 'Instagram reel').slice(0, 60)}...`,
        aiSummary: `This simulated article was generated from Instagram reel ${shortcode}. ${caption || ''}`,
        biasAudit: 'Simulation bypasses real AI audit — this is a test article.',
        fullBlog: `<p class="blog-lead">Simulation mode active. Original Instagram caption: "${caption || 'No caption'}"</p><p>This article was generated by the Instagram automation webhook for testing purposes.</p>`
      };
    }

    // Classify region
    const articleRegion = classifyRegion(caption || 'Instagram Video Update', aiOutput.aiSummary, aiOutput.fullBlog, `Instagram (${config.handle || '@honestlybiased'})`, permalink || `https://www.instagram.com/p/${shortcode}/`);

    const newArticle = {
      id: `instagram_${Date.now()}`,
      category: aiOutput.category || 'Politics',
      region: articleRegion,
      aiHeadline: aiOutput.aiHeadline,
      aiSummary: aiOutput.aiSummary,
      biasAudit: aiOutput.biasAudit,
      fullBlog: aiOutput.fullBlog || '',
      originalSource: `Instagram (${config.handle || '@honestlybiased'})`,
      originalTitle: caption || 'Instagram Video Update',
      timeAgo: new Date().toLocaleTimeString('en-IN', { timeZone: 'Asia/Kolkata', hour: '2-digit', minute: '2-digit', hour12: true }) + ' IST',
      author: 'Honestly Biased AI Engine (Instagram Ingestion)',
      authorType: 'instagram',
      instagramShortcode: shortcode,
      publishdate: new Date().toISOString(),
      imageurl: './assets/hero-bg.png',
      originalurl: permalink || `https://www.instagram.com/p/${shortcode}/`
    };

    // Insert into articles table
    const { data: saved, error } = await supabase
      .from('articles')
      .insert(newArticle)
      .select()
      .single();

    if (error) throw error;

    await supabase.from('instagram_logs').insert({
      message: `[Webhook] Created article: ${saved.aiheadline}`,
      created_at: new Date().toISOString()
    });

    return res.json({ 
      message: 'Webhook processed successfully',
      article: saved
    });

  } catch (err) {
    console.error('Instagram webhook error:', err);
    await supabase.from('instagram_logs').insert({
      message: `[Webhook Error] ${err.message}`,
      created_at: new Date().toISOString()
    }).catch(() => {});
    return res.status(500).json({ error: err.message || 'Webhook processing failed' });
  }
};